### ISSUE TITLE
Structure code to allow for stat organization shift across Lustre versions

### ISSUE THREAD

**Issue by beevans** [whamcloud/lustrefs-exporter#2]
In the past, Lustre stats have changed from version to version.  The end user typically doesn't know (or want to know) about these changes, but our tool should be structured to handle reading changes to things like the location or contents of files as Lustre evolves.  Currently it looks like it's structured for the current version of Lustre only.

**Comment by RDruon** [comment]
I think we can leverage xml definition from https://github.com/DDNStorage/LustrePerfMon/tree/master/xml_definition for this

**Comment by RDruon** [comment]
I think this issue should be moved to https://github.com/whamcloud/lustre-collector as it's the crate that reads the Lustre metrics

**Comment by jgrund** [comment]
I think at the very least we could publish releases matching the Lustre version they are targeting so it's clear what collector version is meant to work with what lustre version

**Comment by jgrund** [comment]
There is no current need to implement this. We'll likely publish releases if we want to enforce matching to Lustre versions for now
